# -*- mode: shell-script -*-

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

bindkey -N mymap emacs
bindkey -A mymap main
# bindkey -r '^L'  # disable obsessive screen clearing
bindkey '^U' backward-kill-line

WORDCHARS=""

function my-backward-kill-word () {
    local WORDCHARS="*?_-.[]~=/&;!#$%^(){}<>"
    zle backward-kill-word
}
zle -N my-backward-kill-word
bindkey '^W' my-backward-kill-word

setopt auto_cd
setopt interactive_comments


#
# History
#
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt extended_history
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history
# See zsh-history-substring-search.zsh below


#
# Prompt
#
source /usr/lib/git-core/git-sh-prompt
setopt prompt_subst
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
# '%(1j.%F{white}* .)' conditional for background jobs
PROMPT='%(1j.%F{white}* .)%F{blue}%~%f %F{242}$(__git_ps1 %s)%f
%F{white}❯%f '


#
# Completion System
#
autoload -Uz compinit; compinit
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''

eval "$(dircolors -b)"
setopt auto_list
setopt list_ambiguous
zmodload -i zsh/complist
bindkey -M menuselect '^M' .accept-line
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


# Ensure path arrays do not contain duplicates
typeset -gU cdpath fpath mailpath path
path=(
    ~/.bin
    ~/.local/bin
    ~/.rvm/bin
    /usr/local/bin
    /snap/bin
    $path
)

export LANG='en_US.UTF-8'
export EDITOR=emacsclient
export VISUAL=emacsclient
export PAGER=most
export BROWSER=google-chrome

export SANE_DEFAULT_DEVICE="genesys:libusb:001:018"
export EMACS_SERVER_SOCK="/tmp/emacs$(id -u)/server"
export GPG_TTY=$(tty)
export VIRTUAL_ENV_DISABLE_PROMPT=""

export KEYID=0x2A946D7DC9CB2D74
export BACKGROUNDS=~/keep/backgrounds

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls -lh --color --group-directories-first'
alias wget_head='wget -qSO /dev/null'
alias feh="feh --auto-zoom --action1 'fbsetbg -a %f'"
alias emacs=emacsclient
alias dropbox="sudo docker run -d --restart=always --name=dropbox -v $HOME/Dropbox:/dbox/Dropbox janeczku/dropbox"
alias ssh="ssh -R ~/.ssh/emacs-server:$EMACS_SERVER_SOCK"
alias ansible_check_deployed_code="ansible all -m shell -a 'cd ~bcd/mobot && git log -1 --pretty=oneline --abbrev-commit --decorate'"
alias xfce4-terminal='xfce4-terminal --disable-server'

alias mutt='mutt -F ~/.mutt/profiles/zoion/main'
alias mmutt='mutt -F ~/.mutt/profiles/teammobot/main'

alias cls=clear

# Clojure dev stuff
alias lt='lein test'
alias ltr='lein test-refresh'
alias ltc='lein with-profile test cloverage'

alias vpn='sudo openvpn --config /etc/openvpn/mobot.conf'

source ~/.zsh_functions

#
# Should be last
#

# Debian zsh-syntax-highlighting package
ZSH_HIGHLIGHT_HIGHLIGHTERS=(brackets)  # additional types: main pattern cursor
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# https://github.com/zsh-users/zsh-history-substring-search
source ~/.zshlib/zsh-history-substring-search.zsh
bindkey "$key[Up]" history-substring-search-up
bindkey "$key[Down]" history-substring-search-down

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
