# -*- mode: shell-script -*-

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# path defined in zprofile
if [ -f $HOME/.zprofile ]; then . $HOME/.zprofile; fi

export LANG='en_US.UTF-8'
export EDITOR=emacsclient
export VISUAL=emacsclient
export PAGER=most
export EMACS_SERVER_SOCK="/tmp/emacs$(id -u)/server"
export FZF_DEFAULT_OPTS="--tmux 75%,50% --layout=reverse --color='pointer:green'"

bindkey -N mymap emacs
bindkey -A mymap main
bindkey '^U' backward-kill-line
bindkey -r '^L'  # disable obsessive screen clearing

function my-backward-kill-word () {
    local WORDCHARS="*?_-.[]~=/&;!#$%^(){}<>"
    zle backward-kill-word
}
zle -N my-backward-kill-word
bindkey '^W' my-backward-kill-word

setopt auto_cd
setopt pushd_ignore_dups
setopt interactive_comments
setopt rm_star_silent


#
# History
#
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt extended_history
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history

# Load zsh-history-substring-search package
_pkg=/opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
if [ -e $_pkg ]; then
    source $_pkg
    bindkey '^[[A' history-substring-search-up  # up arrow
    bindkey '^[[B' history-substring-search-down  # down arrow
fi

bindkey '^r' fzf-history-widget


#
# Completion System
#
eval "$(dircolors -b)"

autoload -Uz compinit; compinit
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''

setopt auto_list
setopt list_ambiguous
zmodload -i zsh/complist
bindkey -M menuselect '^M' .accept-line
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,Cmdr'

# Load Bash completion compatibility after Zsh completion
autoload -U +X bashcompinit && bashcompinit

# Tool completion packages
_pkg=$HOME/.asdf/completions/asdf.bash
[ -f $_pkg ] && source $_pkg

_pkg=$HOME/google-cloud-sdk/completion.zsh.inc
[ -f $_pkg ] && source $_pkg

command -v kubectl >/dev/null 2>&1 && source <(kubectl completion zsh)

# Load zsh-syntax-highlighting package
_pkg=/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
if [ -e $_pkg ]; then
    source $_pkg  # Source the plugin first
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

    # Reset and only add some minor highlighting
    ZSH_HIGHLIGHT_STYLES=()
    ZSH_HIGHLIGHT_STYLES[arg0]='fg=white'  # initial tokens
    ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=white,bold'
    ZSH_HIGHLIGHT_STYLES[precommand]='fg=white,underline'  # eg: sudo
    ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=blue'
    ZSH_HIGHLIGHT_STYLES[redirection]='fg=yellow'
    ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=yellow'
    ZSH_HIGHLIGHT_STYLES[comment]='fg=black,bg=white'
fi

# Excellent fuzzy-finder
command -v fzf >/dev/null 2>&1 && source <(fzf --zsh)

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls -lh --color=auto --group-directories-first'
alias emacs=emacsclient
alias cls=clear  # a concession to having disabled ^L
# Clojure dev
alias lt='lein test'
alias ltr='lein test-refresh'
alias ltc='lein with-profile test cloverage'
# Kubernetes
alias kc=kubectl
alias kx=kubectx
alias kxn="kubectx --unset >/dev/null 2>&1"
alias kn=kubens

source ~/.zsh_functions
source ~/.zsh_functions_local

# starship package
eval "$(starship init zsh)"
