# xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap
xset mouse 7/6 0
unclutter -idle 2 -root &
sudo /usr/bin/sensei-raw-ctl --intensity low
sudo /usr/bin/sensei-raw-ctl --pulsation steady
start-pulseaudio-x11
xscreensaver -no-splash &
st -g 114x61+29-36 &
# Uses emacs-desktop to remember windows position and buffer state.
# emacs &
exec fluxbox -log ~/.fluxbox/log
