export PATH="~/.bin:~/.local/bin:$PATH"
export PA_DEF_SINK="alsa_output.pci-0000_00_1f.3.analog-stereo"
export BROWSER=google-chrome

agent_sock=$(gpgconf --list-dirs agent-socket)
export GPG_AGENT_INFO=${agent_sock}:0:1
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap

xset mouse 7/6 0
unclutter -idle 2 -root &
sudo /usr/bin/sensei-raw-ctl --intensity low
sudo /usr/bin/sensei-raw-ctl --pulsation steady

start-pulseaudio-x11
xscreensaver -no-splash &

st -g 114x61+29-36 &

# Uses emacs-desktop to remember windows position and buffer state.
# emacs &

exec fluxbox -log ~/.fluxbox/log
