# -*- mode:conf -*-

# eval $(dbus-launch --exit-with-x11 --sh-syntax)
# dbus-update-activation-environment --verbose --systemd DBUS_SESSION_BUS_ADDRESS

export PATH="~/.bin:~/.local/bin:$PATH"
export PA_DEF_SINK="alsa_output.pci-0000_00_1f.3.analog-stereo"
export BROWSER=google-chrome

agent_sock=$(gpgconf --list-dirs agent-socket)
export GPG_AGENT_INFO=${agent_sock}:0:1
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap

xset mouse 7/6 0
unclutter -idle 2 -root &
xwallpaper --maximize $(cat ~/.wallpaper)
sudo /usr/bin/sensei-raw-ctl --intensity low
sudo /usr/bin/sensei-raw-ctl --pulsation steady

compton -b
start-pulseaudio-x11
xscreensaver -no-splash &
run_keybase -g

st &
emacs &

exec dwm
