#!/bin/bash

export PATH="$HOME/.bin:$HOME/.local/bin:$PATH"
export BROWSER=google-chrome

source ~/.xsession.local

xmodmap ~/.Xmodmap

xset mouse 7/6 0
unclutter -idle 2 -root &
xwallpaper --maximize "$(cat ~/.wallpaper)"
sudo /usr/bin/sensei-raw-ctl --intensity low
sudo /usr/bin/sensei-raw-ctl --pulsation steady

compton -b
start-pulseaudio-x11
xscreensaver -no-splash &
blueman-applet &
# run_keybase -g >/dev/null
# dwm_clock.sh &

st &
emacs &

fluxbox

# if command -v dwm >/dev/null ; then
#     # bar -d &
#     while command -v dwm ; do dwm && break || continue ; done
# fi
